// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ara.Infrastructure.Persistence;

#nullable disable

namespace Ara.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AraDbContext))]
    partial class AraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ara.Domain.Entities.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Island")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("destinations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Turquoise lagoon and overwater bungalows.",
                            Island = "Society Islands",
                            Name = "Bora Bora",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Description = "Black sand beaches and the gateway to French Polynesia.",
                            Island = "Society Islands",
                            Name = "Tahiti",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Description = "Jagged volcanic peaks overlooking a coral reef.",
                            Island = "Society Islands",
                            Name = "Moorea",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Description = "One of the largest atolls in the world, prized for diving.",
                            Island = "Tuamotu Archipelago",
                            Name = "Rangiroa",
                            Rating = 4.7000000000000002
                        });
                });

            modelBuilder.Entity("Ara.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_email_contains_at", "\"Email\" LIKE '%@%'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
